name: Terraform Plan & Apply

on:
  pull_request:
    paths:
      - 'infra/**'
  push:
    branches:
      - main
    paths:
      - 'infra/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, prod]
    environment: terraform-${{ matrix.env }}
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_STATE_LOCK_TABLE: ${{ secrets.TF_STATE_LOCK_TABLE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Fmt
        run: terraform -chdir=infra/terraform/envs/${{ matrix.env }} fmt -check

      - name: Terraform Init
        run: >-
          terraform -chdir=infra/terraform/envs/${{ matrix.env }} init
          -backend-config="bucket=${{ env.TF_STATE_BUCKET }}"
          -backend-config="key=${{ matrix.env }}/terraform.tfstate"
          -backend-config="dynamodb_table=${{ env.TF_STATE_LOCK_TABLE }}"
          -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        run: terraform -chdir=infra/terraform/envs/${{ matrix.env }} validate

      - name: Terraform Plan
        run: terraform -chdir=infra/terraform/envs/${{ matrix.env }} plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ matrix.env }}
          path: infra/terraform/envs/${{ matrix.env }}/tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=infra/terraform/envs/${{ matrix.env }} apply -auto-approve tfplan
